### ISSUE TITLE
아두이노 bluetooth 페어링 문제

### ISSUE THREAD

**Issue by tjwotmd1** [2021-SMHRD-KDT-IoT-4/DodamDodam#11]
1.마스터  슬레이브1 통신후

다른 슬레이브2와 통신 여부

2.무선랜카드 관련

**Comment by nayeho** [comment]
1. 1:1 페어링 이외의 기술은 3차때 습득, 다른 방안 찾아보는 중
2. 노트북을 통해 무선랜카드 대체
